# WINTER WINING CAMP
##   DAY 1
##SUM OF FIRST N NATURAL NUMBERS

In [ ]:
if __name__ == "__main__":
    n = int(input("Enter a number: "))
    sum=0
    for i in range(1, n+1):
        sum += i
    print("Sum of natural numbers up to {} is: {}".format(n, sum))

##PRIME OR NON PRIME NUMBERS

In [ ]:
def prime_num(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    for i in range(5, int(n ** 0.5) + 1, 6):
        if n % i == 0 or n % (i + 2) == 0:
            return False
    return True


if __name__ == "__main__":
    n = int(input("Enter a number: "))
    result = prime_num(n)
    print(f"The number {n} is {'a prime number' if result else 'not a prime number'}.")

##SUM OF ODD NATURAL NUMBERS UPTO N


In [ ]:
def odd_sum(n):
    sum = 0
    if n % 2 != 0:
        for i in range(1, n + 1, 2):
            sum += i
        print("Sum of odd natural numbers up to {} is: {}".format(n, sum))
    else:
        print("{} is not an odd number. Please enter an odd number.".format(n))

if __name__ == "__main__":
    n = int(input("Enter a number: "))
    result = odd_sum(n)

##LENGTH OF A NUMBER

In [ ]:
if __name__ == "__main__":
    n = int(input("Enter a number: "))
    count = 0
    num = abs(n)

    while num > 0:
        num //= 10
        count += 1

    print("The length of the number is:", count)

##REVERSE A NUMBER

In [ ]:
def reverse(n):
    rev=0
    while n>0:
        rem=n%10
        rev=rev*10+rem
        n=n//10
    return rev

if __name__=="__main__":
    n=int(input("enter a number: "))
    result=reverse(n)
    print(result)

enter a number: 7593
3957


##AREA OF DIFFFERENT SHAPES

In [ ]:
class Calculate:
    def __init__(self):
        self.result = None

    def circle_area(self, radius):
        self.result = 3.14 * (radius ** 2)
        return self.result

    def rectangle_area(self, length, breadth):
        self.result = length * breadth
        return self.result

    def triangle_area(self, base, height):
        self.result = 0.5 * base * height
        return self.result

if __name__ == "__main__":
    calc = Calculate()
    print("Circle Area:", calc.circle_area(5))
    print("Rectangle Area:", calc.rectangle_area(10, 20))
    print("Triangle Area:", calc.triangle_area(5, 10))

## Banking

In [3]:
class Account:
    def __init__(self, balance):
        self.balance = balance

    def calculate_interest(self):
        raise NotImplementedError("Subclasses must implement the calculate_interest method")


class SavingsAccount(Account):
    def calculate_interest(self):
        rate = float(input("Enter the rate of interest (as percentage): "))
        time = float(input("Enter the time (in years): "))
        interest = (self.balance * rate * time) / 100
        return f"Savings Account Interest: {interest}"


class CurrentAccount(Account):
    def calculate_interest(self):
        fee = float(input("Enter maintenance fee: "))
        self.balance -= fee
        return f"Balance after fee deduction: {self.balance}"


if __name__ == "__main__":
    balance = int(input("Enter the balance: "))
    acc = input("Enter the account type (savings/current): ").lower()

    if acc == "savings":
        s = SavingsAccount(balance)
        print(s.calculate_interest())
    elif acc == "current":
        c = CurrentAccount(balance)
        print(c.calculate_interest())
    else:
        print("Invalid account type.")

Enter the balance: 300000
Enter the account type (savings/current): savings
Enter the rate of interest (as percentage): 6
Enter the time (in years): 5
Savings Account Interest: 90000.0


## MATRIX

In [1]:
import numpy as np

if __name__=="__main__":
    a1=np.array([[13,5,6],[4,8,2],[23,54,78]])
    a2=np.array([[1,8,64],[5,83,32],[3,4,8]])

    print("array1: ","\n", a1)
    print("\n")
    print("array2: ","\n", a2)
    print("\n")
    print("Addition: ","\n", a1+a2)
    print("\n")
    print("Subtraction: ","\n", a1-a2)
    print("\n")
    print("Multiplication: ","\n", a1*a2)

array1:  
 [[13  5  6]
 [ 4  8  2]
 [23 54 78]]


array2:  
 [[ 1  8 64]
 [ 5 83 32]
 [ 3  4  8]]


Addition:  
 [[14 13 70]
 [ 9 91 34]
 [26 58 86]]


Subtraction:  
 [[ 12  -3 -58]
 [ -1 -75 -30]
 [ 20  50  70]]


Multiplication:  
 [[ 13  40 384]
 [ 20 664  64]
 [ 69 216 624]]
